#ifndef EMXAPI_COMM_RINGBUF_CONFIG_H
#define EMXAPI_COMM_RINGBUF_CONFIG_H

#ifndef EMX_RINGBUF_ALIGN
#define EMX_RINGBUF_ALIGN 8
#endif

#ifndef EMX_RINGBUF_SIZE
#define EMX_RINGBUF_SIZE 64*1024
#endif

#endif
