name: "Nix"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [sequential, parallel]
        target: [native, cross]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: aeronautical-informatics
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#qsma-${{ matrix.kind }}-${{ matrix.target }} --print-build-logs
      - uses: actions/upload-artifact@v3
        with:
          name: qsma-${{ matrix.kind }}-${{ matrix.target}}
          path: result/**
